apiVersion: v1
kind: Service
metadata:
  name: {{ include "site.fullname" . }}
  labels:
    {{- include "site.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
      name: http-{{ . }}
    {{- end }}
  selector:
    {{- include "site.selectorLabels" . | nindent 4 }}
