hb:
  terms:
    paginate: 12
  blog:
    full_width: false
    paginate: 12
    post_date_format: ":date_long"
    post_thumbnail: true
    post_thumbnail_default: "images/thumbnail.png"
    post_thumbnail_placeholder: ""
    list_cols_md: 2
    list_cols_lg: 3
    toc:
      position: end
    home:
      taxonomies: true
      featured_posts: 5
      main_sections:
        - docs
        - blog
    archives:
      paginate: 30
